version: 0.0
os: linux
files:
  - source: ./public
    destination: /srv/www/myhome
permissions:
  - object: /deploy
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - file
permissions:
  - object: .
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
hooks:
  BeforeInstall:
    - location: ./deploy/before-install.sh
      timeout: 100
      runas: ubuntu
  AfterInstall:
    - location: ./deploy/after-install.sh
      timeout: 100
      runas: ubuntu