version: 0.0
os: linux
files:
  - source: /
    destination: /var/node/myhome
hooks:
  BeforeInstall:
    - location: deploy/before-install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: deploy/after-install.sh
      timeout: 300
      runas: ec2-user
